# Generated by Django 3.0.8 on 2020-07-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20200726_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
