# Generated by Django 3.0.8 on 2020-07-27 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_comment_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created',
            new_name='date_created',
        ),
    ]
